// Generated by CoffeeScript 1.3.3
(function() {
  var Board, Piece,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Board = (function(_super) {

    __extends(Board, _super);

    function Board() {
      return Board.__super__.constructor.apply(this, arguments);
    }

    Board.configure("size", "state");

    return Board;

  })(Spine.Model);

  Piece = (function(_super) {

    __extends(Piece, _super);

    function Piece() {
      return Piece.__super__.constructor.apply(this, arguments);
    }

    Piece.configure("color", "position");

    return Piece;

  })(Spine.Model);

}).call(this);
